# SilkLens — top-level Makefile.
# Aggregates per-service tasks so contributors only need one entry point.

.PHONY: help dev down logs ps api-install api-run api-test api-test-random api-test-parallel api-test-cov api-lint api-format api-mypy api-mypy-strict api-bandit api-bandit-all api-migrate api-revision api-shell admin-test admin-knip mobile-analyze clean install-hooks trivy-install api-trivy-image sbom license-check security

help: ## Show this help
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

# --- Infra ---

dev: ## Start the local dev docker stack (postgres, redis, minio, es, redpanda)
	docker compose -f infra/docker/docker-compose.yml up -d

down: ## Stop the local dev stack
	docker compose -f infra/docker/docker-compose.yml down

logs: ## Tail dev stack logs
	docker compose -f infra/docker/docker-compose.yml logs -f --tail=100

ps: ## Show dev stack status
	docker compose -f infra/docker/docker-compose.yml ps

# --- API service ---

api-install: ## Install API service deps into a local .venv (requires libmagic1 + libpq-dev system pkgs)
	cd services/api && python -m venv .venv && .venv/bin/pip install -U pip && .venv/bin/pip install -e ".[dev]"

api-run: ## Run the API locally (foreground)
	cd services/api && .venv/bin/python -m src

api-test: ## Run API tests (linear, randomized order via pytest-randomly)
	cd services/api && .venv/bin/pytest -ra

api-test-random: ## Re-run tests with the LAST failing random seed (debug order-dependency)
	cd services/api && .venv/bin/pytest -ra --randomly-seed=last

api-test-parallel: ## Run tests in parallel (pytest-xdist) + random order — finds parallel-safety bugs
	cd services/api && .venv/bin/pytest -n auto -ra

api-test-cov: ## Run API tests with coverage
	cd services/api && .venv/bin/pytest --cov=src --cov-report=term-missing --cov-report=html

api-lint: ## Lint the API
	cd services/api && .venv/bin/ruff check src tests

api-format: ## Auto-format the API
	cd services/api && .venv/bin/ruff format src tests && .venv/bin/ruff check --fix src tests

api-mypy: ## Type-check the API
	cd services/api && .venv/bin/mypy src

api-mypy-strict: ## Type-check the API with --strict (no pyproject overrides) — finds hidden type bugs
	cd services/api && .venv/bin/mypy src --strict --no-incremental --config-file=/dev/null

api-bandit: ## Security lint the API with bandit (HIGH+ severity blocks; same as CI)
	cd services/api && .venv/bin/bandit -r src -c pyproject.toml --severity-level high --confidence-level medium

api-bandit-all: ## Run bandit at LOW severity / LOW confidence (every finding) — local audit only
	cd services/api && .venv/bin/bandit -r src -c pyproject.toml -l -i

admin-test: ## Run admin unit tests (Vitest — pure logic, no browser)
	cd apps/admin && pnpm test

admin-knip: ## Detect dead code / unused exports / orphan files in admin
	cd apps/admin && pnpm knip

mobile-analyze: ## Run Flutter analyzer (--fatal-warnings --fatal-infos for CI)
	cd apps/mobile && flutter analyze --fatal-warnings --fatal-infos lib/

install-hooks: ## Install pre-push + pre-commit git hooks (run once after clone)
	bash scripts/install-hooks.sh

api-migrate: ## Apply Alembic migrations
	cd services/api && .venv/bin/alembic upgrade head

api-downgrade: ## Roll back one migration
	cd services/api && .venv/bin/alembic downgrade -1

api-revision: ## Create a new Alembic revision (make api-revision m="message")
	cd services/api && .venv/bin/alembic revision -m "$(m)"

api-revision-auto: ## Create an autogenerated Alembic revision (make api-revision-auto m="message")
	cd services/api && .venv/bin/alembic revision --autogenerate -m "$(m)"

api-shell: ## Drop into an interactive Python shell with app context
	cd services/api && .venv/bin/ipython

# --- Security ---
#
# Requires trivy: run `make trivy-install` once, or let the targets auto-install.
# Docker must be running for `api-trivy-image`.

trivy-install: ## Download and install Trivy to /usr/local/bin (requires sudo)
	curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
	  | sudo sh -s -- -b /usr/local/bin
	trivy --version

api-trivy-image: ## Build API image and scan for OS + package CVEs (HIGH/CRITICAL)
	@which trivy > /dev/null 2>&1 || $(MAKE) trivy-install
	docker build -t silklens-api:local services/api/
	trivy image \
	  --severity HIGH,CRITICAL \
	  --ignore-unfixed \
	  --scanners vuln,misconfig \
	  --exit-code 1 \
	  silklens-api:local

sbom: ## Generate CycloneDX SBOMs → sbom-api.cdx.json + sbom-admin.cdx.json
	@which trivy > /dev/null 2>&1 || $(MAKE) trivy-install
	trivy fs services/api --format cyclonedx --output sbom-api.cdx.json   --scanners vuln --quiet
	trivy fs apps/admin   --format cyclonedx --output sbom-admin.cdx.json --scanners vuln --quiet
	@echo "✅  SBOMs written: sbom-api.cdx.json, sbom-admin.cdx.json"

license-check: ## Scan all deps for copyleft / incompatible licenses (fail on CRITICAL/HIGH)
	@which trivy > /dev/null 2>&1 || $(MAKE) trivy-install
	@echo "--- API (Python) ---"
	trivy fs services/api --scanners license --license-full --severity CRITICAL,HIGH --exit-code 1 --format table
	@echo "--- Admin (Node) ---"
	trivy fs apps/admin   --scanners license --license-full --severity CRITICAL,HIGH --exit-code 1 --format table
	@echo "✅  License compliance: no CRITICAL/HIGH violations"

security: api-trivy-image sbom license-check ## Run all local security scans (image + SBOM + licenses)

# --- Hygiene ---

clean: ## Remove caches and build artefacts (keeps Docker volumes)
	find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name .pytest_cache -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name .ruff_cache -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name .mypy_cache -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name htmlcov -exec rm -rf {} + 2>/dev/null || true
	find . -type f -name '.coverage' -delete 2>/dev/null || true
