// This file is regenerated by `flutter gen-l10n` from the .arb files in
// this folder. It is checked in so the project compiles before the first
// run of build_runner / gen-l10n on a fresh checkout.
//
// DO NOT hand-edit lasting changes here — edit the .arb files instead and
// run `flutter gen-l10n` (or `flutter pub get`).

import "package:flutter/foundation.dart";
import "package:flutter/widgets.dart";
import "package:flutter_localizations/flutter_localizations.dart";

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations? of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations);

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = <Locale>[
    Locale("en"),
    Locale("uz"),
    Locale("ru"),
    Locale("zh"),
  ];

  String get appName => _resolve("appName");
  String get appTagline => _resolve("appTagline");
  String get onboardingTitle => _resolve("onboardingTitle");
  String get onboardingSubtitle => _resolve("onboardingSubtitle");
  String get onboardingCta => _resolve("onboardingCta");
  String get onboardingSkip => _resolve("onboardingSkip");
  String get navMap => _resolve("navMap");
  String get navCamera => _resolve("navCamera");
  String get navProfile => _resolve("navProfile");
  String get cameraPlaceholderTitle => _resolve("cameraPlaceholderTitle");
  String get cameraPlaceholderBody => _resolve("cameraPlaceholderBody");
  String get mapPlaceholderTitle => _resolve("mapPlaceholderTitle");
  String get mapPlaceholderBody => _resolve("mapPlaceholderBody");
  String get profileTitle => _resolve("profileTitle");
  String get profileLanguage => _resolve("profileLanguage");
  String get profileTheme => _resolve("profileTheme");

  String _resolve(String key) {
    final bundle = _bundles[locale.languageCode] ?? _bundles["en"]!;
    return bundle[key] ?? _bundles["en"]![key] ?? key;
  }

  // The maps below are seeded with the English fallback so the app boots
  // before `flutter gen-l10n` regenerates this file. The generator will
  // overwrite this entire file using the .arb sources on next pub get.
  static const Map<String, Map<String, String>> _bundles =
      <String, Map<String, String>>{
    "en": <String, String>{
      "appName": "SilkLens",
      "appTagline": "See the Silk Road through your lens",
      "onboardingTitle": "Discover heritage with your camera",
      "onboardingSubtitle":
          "Point at any monument to instantly learn its story.",
      "onboardingCta": "Start exploring",
      "onboardingSkip": "Skip",
      "navMap": "Map",
      "navCamera": "Camera",
      "navProfile": "Profile",
      "cameraPlaceholderTitle": "Camera",
      "cameraPlaceholderBody": "Vision pipeline ships in FAZA 2 — Hafta 3.",
      "mapPlaceholderTitle": "Map",
      "mapPlaceholderBody":
          "Mapbox / OSM integration ships in FAZA 2 — Hafta 3.",
      "profileTitle": "Profile",
      "profileLanguage": "Language",
      "profileTheme": "Theme",
    },
    "uz": <String, String>{
      "appName": "SilkLens",
      "appTagline": "Ipak yo‘lini linzangiz orqali ko‘ring",
      "onboardingTitle": "Kamera orqali madaniy merosni kashf eting",
      "onboardingSubtitle":
          "Istalgan obidaga moslang — uning hikoyasi darhol ochiladi.",
      "onboardingCta": "Kashf etishni boshlash",
      "onboardingSkip": "O‘tkazib yuborish",
      "navMap": "Xarita",
      "navCamera": "Kamera",
      "navProfile": "Profil",
      "cameraPlaceholderTitle": "Kamera",
      "cameraPlaceholderBody": "Vision pipeline FAZA 2 — Hafta 3’da chiqadi.",
      "mapPlaceholderTitle": "Xarita",
      "mapPlaceholderBody":
          "Mapbox / OSM integratsiyasi FAZA 2 — Hafta 3’da chiqadi.",
      "profileTitle": "Profil",
      "profileLanguage": "Til",
      "profileTheme": "Mavzu",
    },
    "ru": <String, String>{
      "appName": "SilkLens",
      "appTagline": "Шёлковый путь через объектив",
      "onboardingTitle": "Исследуйте наследие с помощью камеры",
      "onboardingSubtitle":
          "Наведите камеру на памятник — узнайте его историю мгновенно.",
      "onboardingCta": "Начать исследование",
      "onboardingSkip": "Пропустить",
      "navMap": "Карта",
      "navCamera": "Камера",
      "navProfile": "Профиль",
      "cameraPlaceholderTitle": "Камера",
      "cameraPlaceholderBody":
          "Распознавание появится в FAZA 2 — неделя 3.",
      "mapPlaceholderTitle": "Карта",
      "mapPlaceholderBody":
          "Интеграция Mapbox / OSM появится в FAZA 2 — неделя 3.",
      "profileTitle": "Профиль",
      "profileLanguage": "Язык",
      "profileTheme": "Тема",
    },
    "zh": <String, String>{
      "appName": "SilkLens",
      "appTagline": "用镜头看丝绸之路",
      "onboardingTitle": "用相机探索文化遗产",
      "onboardingSubtitle": "对准任何古迹,立刻了解它的故事。",
      "onboardingCta": "开始探索",
      "onboardingSkip": "跳过",
      "navMap": "地图",
      "navCamera": "相机",
      "navProfile": "个人资料",
      "cameraPlaceholderTitle": "相机",
      "cameraPlaceholderBody": "视觉识别将在 FAZA 2 — 第3周 发布。",
      "mapPlaceholderTitle": "地图",
      "mapPlaceholderBody": "Mapbox / OSM 集成将在 FAZA 2 — 第3周 发布。",
      "profileTitle": "个人资料",
      "profileLanguage": "语言",
      "profileTheme": "主题",
    },
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => <String>{"en", "uz", "ru", "zh"}.contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture<AppLocalizations>(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
