"""payment_methods + intents + payments + webhook idempotency + invoices + refunds + chargebacks

Per Agent 6 monetization architecture §3.5–§3.6:

  payment_methods         — provider-tokenized payment instruments (NEVER raw PAN).
                            provider_token is opaque vault pointer — no PCI scope
                            in this DB (Agent 6 §7).
  payment_intents         — idempotent kick-off records keyed on idempotency_key.
                            Per Agent 6 §3 risk #1: stores the FX snapshot used
                            at charge time so refunds use the SAME rate.
  payments                — actual provider captures. UNIQUE(provider, charge_id)
                            prevents double-record from re-delivered webhooks.
  payment_webhook_events  — provider event de-dupe. Per Agent 6 §3 risk #4 +
                            §7: provider event_id is the idempotency key — every
                            replay short-circuits.
  invoices / invoice_lines — accounting records. Numbers generated by a trigger
                            from a tenant-scoped sequence (Agent 6 §3 — never
                            recompute, never reuse numbers).
  refunds                 — captured refunds (full or partial).
  chargebacks             — disputed transactions tracked through inquiry →
                            disputed → won|lost lifecycle.

Money columns: ``numeric(20, 4)``; FX rates: ``numeric(20, 10)``.

Revision ID: 0052_payments_invoicing
Revises: 0051_subscriptions
Create Date: 2026-05-18
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0052_payments_invoicing"
down_revision: str | Sequence[str] | None = "0051_subscriptions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --- payment_methods (tokenized; NEVER raw PAN) ----------------------
    op.execute(
        """
        CREATE TABLE payment_methods (
            id                  uuid PRIMARY KEY DEFAULT gen_uuid_v7(),
            user_id             uuid NOT NULL,
            residency_region    text NOT NULL,
            provider            text NOT NULL CHECK (provider IN (
                'stripe','payme','click','apple_iap','google_iap','paypal'
            )),
            provider_token      text NOT NULL,
            kind                text NOT NULL CHECK (kind IN (
                'card','wallet','bank_transfer','in_app'
            )),
            last4               text,
            brand               text,
            expires_at          timestamptz,
            is_default          boolean NOT NULL DEFAULT false,
            created_at          timestamptz NOT NULL DEFAULT now(),
            updated_at          timestamptz NOT NULL DEFAULT now(),
            deleted_at          timestamptz,
            FOREIGN KEY (user_id, residency_region)
                REFERENCES users(id, residency_region) ON DELETE CASCADE,
            CHECK (residency_region IN ('uz','eu','us','global')),
            CHECK (last4 IS NULL OR last4 ~ '^[0-9]{4}$')
        );

        CREATE INDEX idx_payment_methods_user
            ON payment_methods (user_id, residency_region)
            WHERE deleted_at IS NULL;
        -- One default payment method per user.
        CREATE UNIQUE INDEX uq_payment_methods_default
            ON payment_methods (user_id, residency_region)
            WHERE is_default AND deleted_at IS NULL;

        CREATE TRIGGER tg_payment_methods_updated_at
            BEFORE UPDATE ON payment_methods
            FOR EACH ROW EXECUTE FUNCTION app.tg_set_updated_at();

        COMMENT ON COLUMN payment_methods.provider_token IS
            'Opaque vault pointer (e.g. Stripe pm_xxx). NEVER store raw PAN — '
            'this DB is OUT of PCI scope (Agent 6 §7).';
        """
    )

    # --- payment_intents (idempotent charge initiation) -------------------
    # exchange_rate_snapshot is referenced as a composite (from, to, captured_at)
    # because the snapshot table's PK is composite (immutable temporal record).
    op.execute(
        """
        CREATE TABLE payment_intents (
            id                              uuid PRIMARY KEY DEFAULT gen_uuid_v7(),
            tenant_id                       uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
            user_id                         uuid NOT NULL,
            residency_region                text NOT NULL,
            subscription_id                 uuid REFERENCES subscriptions(id) ON DELETE SET NULL,
            idempotency_key                 text NOT NULL UNIQUE,
            amount                          numeric(20, 4) NOT NULL CHECK (amount >= 0),
            currency                        char(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT,
            -- composite ref to exchange_rate_snapshots (PK is from+to+captured_at)
            fx_from_currency                char(3),
            fx_to_currency                  char(3),
            fx_captured_at                  timestamptz,
            status                          text NOT NULL DEFAULT 'requires_payment' CHECK (status IN (
                'requires_payment','processing','succeeded','canceled','failed'
            )),
            failure_reason                  text,
            created_at                      timestamptz NOT NULL DEFAULT now(),
            updated_at                      timestamptz NOT NULL DEFAULT now(),
            FOREIGN KEY (user_id, residency_region)
                REFERENCES users(id, residency_region) ON DELETE RESTRICT,
            FOREIGN KEY (fx_from_currency, fx_to_currency, fx_captured_at)
                REFERENCES exchange_rate_snapshots (from_currency, to_currency, captured_at)
                ON DELETE RESTRICT,
            CHECK (residency_region IN ('uz','eu','us','global')),
            -- All three FX fields must be supplied together.
            CHECK (
                (fx_from_currency IS NULL AND fx_to_currency IS NULL AND fx_captured_at IS NULL)
                OR
                (fx_from_currency IS NOT NULL AND fx_to_currency IS NOT NULL AND fx_captured_at IS NOT NULL)
            )
        );

        CREATE INDEX idx_payment_intents_user
            ON payment_intents (user_id, residency_region, created_at DESC);
        CREATE INDEX idx_payment_intents_subscription
            ON payment_intents (subscription_id) WHERE subscription_id IS NOT NULL;
        CREATE INDEX idx_payment_intents_pending
            ON payment_intents (status, created_at)
            WHERE status IN ('requires_payment','processing');

        CREATE TRIGGER tg_payment_intents_updated_at
            BEFORE UPDATE ON payment_intents
            FOR EACH ROW EXECUTE FUNCTION app.tg_set_updated_at();

        COMMENT ON COLUMN payment_intents.idempotency_key IS
            'Client-supplied UUID/string. Re-using the SAME key MUST short-circuit '
            'to the existing intent. Agent 6 §3 risk #2.';
        """
    )

    # --- payments (provider captures) ------------------------------------
    op.execute(
        """
        CREATE TABLE payments (
            id                          uuid PRIMARY KEY DEFAULT gen_uuid_v7(),
            intent_id                   uuid NOT NULL REFERENCES payment_intents(id) ON DELETE RESTRICT,
            provider                    text NOT NULL,
            provider_charge_id          text NOT NULL,
            captured_amount             numeric(20, 4) NOT NULL CHECK (captured_amount >= 0),
            currency                    char(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT,
            fee_amount                  numeric(20, 4) NOT NULL DEFAULT 0 CHECK (fee_amount >= 0),
            exchange_rate_at_capture    numeric(20, 10),
            captured_at                 timestamptz NOT NULL DEFAULT now(),
            created_at                  timestamptz NOT NULL DEFAULT now(),
            UNIQUE (provider, provider_charge_id),
            CHECK (exchange_rate_at_capture IS NULL OR exchange_rate_at_capture > 0)
        );

        CREATE INDEX idx_payments_intent
            ON payments (intent_id);
        CREATE INDEX idx_payments_captured_at
            ON payments (captured_at DESC);

        COMMENT ON TABLE payments IS
            'Provider charge records. UNIQUE(provider, charge_id) is the dedup '
            'key — re-delivered webhooks resolve to the same row.';
        """
    )

    # --- payment_webhook_events (provider event de-dupe) -----------------
    op.execute(
        """
        CREATE TABLE payment_webhook_events (
            id                  uuid PRIMARY KEY DEFAULT gen_uuid_v7(),
            provider            text NOT NULL,
            provider_event_id   text NOT NULL,
            event_type          text NOT NULL,
            payload             jsonb NOT NULL,
            received_at         timestamptz NOT NULL DEFAULT now(),
            processed_at        timestamptz,
            error               text,
            UNIQUE (provider, provider_event_id)
        );

        CREATE INDEX idx_payment_webhook_events_unprocessed
            ON payment_webhook_events (received_at)
            WHERE processed_at IS NULL;
        CREATE INDEX idx_payment_webhook_events_type
            ON payment_webhook_events (provider, event_type, received_at DESC);

        COMMENT ON TABLE payment_webhook_events IS
            'Idempotent webhook log per Agent 6 §3 risk #4 + §7. Provider event '
            'id is the unique key — every retry/replay short-circuits.';
        """
    )

    # --- invoice number sequence + invoices ------------------------------
    # Sequence backs trigger-generated invoice numbers. Format: SLN-YYYY-NNNNNNN.
    op.execute(
        """
        CREATE SEQUENCE invoices_number_seq START WITH 100000;

        CREATE TABLE invoices (
            id                  uuid PRIMARY KEY DEFAULT gen_uuid_v7(),
            tenant_id           uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
            user_id             uuid NOT NULL,
            residency_region    text NOT NULL,
            subscription_id     uuid REFERENCES subscriptions(id) ON DELETE SET NULL,
            number              text NOT NULL UNIQUE,
            total               numeric(20, 4) NOT NULL CHECK (total >= 0),
            currency            char(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT,
            status              text NOT NULL DEFAULT 'draft' CHECK (status IN (
                'draft','open','paid','uncollectible','void'
            )),
            period_start        timestamptz,
            period_end          timestamptz,
            issued_at           timestamptz,
            paid_at             timestamptz,
            pdf_url             text,
            created_at          timestamptz NOT NULL DEFAULT now(),
            updated_at          timestamptz NOT NULL DEFAULT now(),
            FOREIGN KEY (user_id, residency_region)
                REFERENCES users(id, residency_region) ON DELETE RESTRICT,
            CHECK (residency_region IN ('uz','eu','us','global')),
            CHECK (period_end IS NULL OR period_start IS NULL OR period_end >= period_start)
        );

        CREATE INDEX idx_invoices_user
            ON invoices (user_id, residency_region, created_at DESC);
        CREATE INDEX idx_invoices_status
            ON invoices (status, created_at DESC);
        CREATE INDEX idx_invoices_subscription
            ON invoices (subscription_id) WHERE subscription_id IS NOT NULL;

        CREATE TRIGGER tg_invoices_updated_at
            BEFORE UPDATE ON invoices
            FOR EACH ROW EXECUTE FUNCTION app.tg_set_updated_at();
        """
    )

    # --- invoice-number generator trigger --------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION app.tg_invoice_number() RETURNS trigger AS $$
        BEGIN
            IF NEW.number IS NULL OR NEW.number = '' THEN
                NEW.number := 'SLN-' || to_char(now(), 'YYYY') || '-'
                           || lpad(nextval('invoices_number_seq')::text, 7, '0');
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER tg_invoices_number
            BEFORE INSERT ON invoices
            FOR EACH ROW EXECUTE FUNCTION app.tg_invoice_number();

        COMMENT ON FUNCTION app.tg_invoice_number IS
            'Generates SLN-YYYY-NNNNNNN invoice numbers from invoices_number_seq. '
            'Numbers are never reused (Agent 6 §3 — accounting integrity).';
        """
    )

    # --- invoice_lines ---------------------------------------------------
    op.execute(
        """
        CREATE TABLE invoice_lines (
            invoice_id      uuid NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
            line_number     int NOT NULL CHECK (line_number > 0),
            description     text NOT NULL,
            quantity        int NOT NULL DEFAULT 1 CHECK (quantity > 0),
            unit_amount     numeric(20, 4) NOT NULL CHECK (unit_amount >= 0),
            total_amount    numeric(20, 4) NOT NULL CHECK (total_amount >= 0),
            tax_amount      numeric(20, 4) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
            plan_id         uuid REFERENCES product_plans(id) ON DELETE SET NULL,
            product_id      uuid REFERENCES products(id) ON DELETE SET NULL,
            PRIMARY KEY (invoice_id, line_number)
        );

        CREATE INDEX idx_invoice_lines_plan
            ON invoice_lines (plan_id) WHERE plan_id IS NOT NULL;
        CREATE INDEX idx_invoice_lines_product
            ON invoice_lines (product_id) WHERE product_id IS NOT NULL;
        """
    )

    # --- refunds ---------------------------------------------------------
    op.execute(
        """
        CREATE TABLE refunds (
            id                  uuid PRIMARY KEY DEFAULT gen_uuid_v7(),
            payment_id          uuid NOT NULL REFERENCES payments(id) ON DELETE RESTRICT,
            amount              numeric(20, 4) NOT NULL CHECK (amount > 0),
            currency            char(3) NOT NULL REFERENCES currencies(code) ON DELETE RESTRICT,
            reason              text,
            provider_refund_id  text,
            status              text NOT NULL DEFAULT 'pending' CHECK (status IN (
                'pending','succeeded','failed'
            )),
            created_at          timestamptz NOT NULL DEFAULT now(),
            processed_at        timestamptz,
            UNIQUE (payment_id, provider_refund_id)
        );

        CREATE INDEX idx_refunds_payment
            ON refunds (payment_id);
        CREATE INDEX idx_refunds_status
            ON refunds (status, created_at DESC);
        """
    )

    # --- chargebacks -----------------------------------------------------
    op.execute(
        """
        CREATE TABLE chargebacks (
            id              uuid PRIMARY KEY DEFAULT gen_uuid_v7(),
            payment_id      uuid NOT NULL REFERENCES payments(id) ON DELETE RESTRICT,
            amount          numeric(20, 4) NOT NULL CHECK (amount > 0),
            reason_code     text,
            status          text NOT NULL DEFAULT 'inquiry' CHECK (status IN (
                'inquiry','disputed','won','lost'
            )),
            opened_at       timestamptz NOT NULL DEFAULT now(),
            resolved_at     timestamptz,
            CHECK (resolved_at IS NULL OR resolved_at >= opened_at)
        );

        CREATE INDEX idx_chargebacks_payment
            ON chargebacks (payment_id);
        CREATE INDEX idx_chargebacks_open
            ON chargebacks (opened_at DESC)
            WHERE status IN ('inquiry','disputed');
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS chargebacks CASCADE;")
    op.execute("DROP TABLE IF EXISTS refunds CASCADE;")
    op.execute("DROP TABLE IF EXISTS invoice_lines CASCADE;")
    op.execute("DROP TRIGGER IF EXISTS tg_invoices_number ON invoices;")
    op.execute("DROP FUNCTION IF EXISTS app.tg_invoice_number();")
    op.execute("DROP TABLE IF EXISTS invoices CASCADE;")
    op.execute("DROP SEQUENCE IF EXISTS invoices_number_seq;")
    op.execute("DROP TABLE IF EXISTS payment_webhook_events CASCADE;")
    op.execute("DROP TABLE IF EXISTS payments CASCADE;")
    op.execute("DROP TABLE IF EXISTS payment_intents CASCADE;")
    op.execute("DROP TABLE IF EXISTS payment_methods CASCADE;")
